### ISSUE TITLE
return a nonzero error code when missing an item in the cache

### ISSUE THREAD

**Issue by ekimia** [blender/Rome#70] opened 2017-05-22 22:33 UTC
#### Enhancement Suggestion

    Main use case: pulling in the cache from CI, seeing there isnt a rome cache, and then moving onto running `carthage update` followed by `rome upload`. 

    **Current and suggested behavior**

Currently it outputs the "could not find .frameworkname.version in local cache at: CACHE_DIR but with a 0 exit code.

    **Why would the enhancement be useful to most users**
Automatically cache and upload if the cache isn't present

    **Rome version:**  0.11.27
    **OS and version:** Sierra

**Comment by ekimia** [comment] 2017-05-22 22:35
Would totally be down to submit a PR but wanted to get the feelers out about this change.

**Comment by blender** [comment] 2017-05-23 06:25
Hi @ekimia, thanks for opining an issue.

If I understand correctly you want to build what is missing in the cache and the upload it. 
This use case is already supported as described in https://github.com/blender/Rome#listing .

What you want to do is list before building list so:
`rome list --missing --platform ios | awk '{print $1}' | xargs carthage build --platform ios  && rome upload --platform ios`

If no frameworks are missing the pipe to awk will fail and the rest of the command will not be executed. This avoids rebuilding all dependencies. For the sake of understanding the complete command you can call list with `--present` to get a feeling for the different steps. 

Does this help in supporting your workflow?

**Comment by blender** [comment] 2017-05-23 08:38
I have opened a PR to enhance the documentation on the CI workflow. Feel free to comment: https://github.com/blender/Rome/blob/fix/ci-workflow-readme/README.md#ci-workflow

**Comment by ekimia** [comment] 2017-05-23 18:46
ah this is perfect! Great idea to enhance the documentation.ar

**Comment by blender** [comment] 2017-05-23 21:27
@ekimia here is the PR https://github.com/blender/Rome/pull/71, let me know if you have comments. 

About exiting with non-zero status from a `download` command there are the following considerations to make:
- exit with non-zero when ANY artifact download fails?
  - each artifact download failure could be encoded as a bit pattern and `OR`ed together in a final error code
    - failing framework: 0x01
    - failing dSYM: 0x02
    - failing `.versionFile`: 0x4 
- exit with non-zero only when framework download fails?

**Comment by netbe** [comment] 2017-05-24 01:49
I would be up for 
> exit with non-zero only when framework download fails?

**Comment by erichoracek** [comment] 2017-05-24 02:06
I think this really depends on what you consider rome's job to be. In my opinion:

If you perform `rome download` and you get a partial hit, this seems like rome did what you asked to the best of its ability. There is no way that `rome` could have succeeded any more concretely beside there more artifacts being present in the cache, which will never change no matter how many times you run `rome download`. As for whether or not this is a non-zero exit status, this depends on whether you think `rome download` means "warm the carthage build folder with cached frameworks" or "download every frameworks, otherwise bail". For me, I interpret it as the former since I see rome as a cache in front of carthage. In my experience with caching APIs, a cache miss is typically not a exception-style failure, just one of two possible successful outcomes (hit/miss).

**Comment by blender** [comment] 2017-05-24 07:43
I agree with @erichoracek , a miss is just one of the possible outcomes, it's not an exceptional failure that terminates the program execution.

For the time being I'll leave things as they are. If the issue is brought up again I'll consider exiting with non-zero status.

@ekimia please consider closing the issue if the explanations I gave about the CI workflow are enough for you.

**Comment by blender** [comment] 2017-05-29 09:40
Closing for now.

**Closed by blender** 2017-05-29 09:40 UTC
Labels: question
