### ISSUE TITLE
Rome do not use env variables

### ISSUE THREAD

**Issue by chika-kasymov** [blender/Rome#149] opened 2018-09-09 08:05 UTC
## Enhancement Suggestion / Bug Report 

    When using environment variables I'm getting the same error both on local and CircleCI: ```rome: /Users/chika/.aws/config: openFile: does not exist (No such file or directory)```.

**Steps which explain the enhancement or reproduce the bug**

1. Setup Rome
2. Export `AWS_REGION`, `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY` variables
3. Run any Rome command

**Current behavior**

    See bug report.

**Suggested behavior**

    Rome should execute commands properly without `.aws/config` and `.aws/credentials` files when necessary environment variables exist.

**Why would the enhancement be useful to most users**

    That is a must-have feature for CI.

**Rome version:** 

    0.17.1.49

**OS and version:** 

    macOS High Sierra 10.13.6

**Comment by blender** [comment] 2018-09-09 08:28
Thanks for opening an issue, this is a duplicate of https://github.com/blender/Rome/issues/102

There is a workaround in that issue. It's not a problem with rome as far as I can tell. Reading env variables should work fine on your machine for example.

**Comment by blender** [comment] 2018-09-09 08:31
Actually you said you get the same problem locally?

**Comment by chika-kasymov** [comment] 2018-09-09 08:34
Yes. I exported AWS variables and see them in `env` command output, but any Rome command fails.

**Closed** 2018-09-09 16:06 UTC
Labels: bug

**Comment by blender** [comment] 2018-09-09 16:09
@chika-kasymov please try https://github.com/blender/Rome/releases/tag/v0.17.2.50

**Comment by chika-kasymov** [comment] 2018-09-10 02:41
@blender sadly the fix doesn't solve the problem on both sides. Currently, I'm getting this error:
```
Failed reading: Failure parsing Region from asfd/Users/chika/.aws/config: openFile: does not exist (No such file or directory)
```
`asdf` here is the value of `AWS_REGION`.

**Comment by blender** [comment] 2018-09-10 04:10
AWS_REGION must be a valid region. asdf is not a valid region

**Comment by blender** [comment] 2018-09-10 04:11
Try with us-east-1 for example

**Comment by chika-kasymov** [comment] 2018-09-10 05:38
@blender sorry I tried `asdf` for testing purposes and didn't know Rome validates the value :) Yes, with correct value everything works now. But I can't get a new version using `brew`. Will it update automatically after a while?

**Comment by blender** [comment] 2018-09-10 05:39
I will release via homebrew in the next 30 minutes and write back here.

**Comment by chika-kasymov** [comment] 2018-09-10 05:41
Thanks!

**Comment by blender** [comment] 2018-09-10 05:59
@chika-kasymov  done
