### ISSUE TITLE
Proxy Error - Connection Refused

### ISSUE THREAD

**Issue by TeddyMalfroy** [blender/Rome#145] opened 2018-08-16 14:27 UTC
## Enhancement Suggestion / Bug Report 

I have a problem with my Ruby script, the script works on a "normal" connection but not in my enterprise with proxy. however it is well configured on my terminal, Help me please !!

**Comment by blender** [comment] 2018-08-16 19:04
Hello, thanks for opening a issue.

What ruby script are you referring to? Rome is not a ruby script.

What do your proxy settings look like?

**Comment by TeddyMalfroy** [comment] 2018-08-17 08:12
Hi, thank you for your answer! 
I created a ruby ​​script calling the function rome upload & download, here is what the proxy looks like: ENV['HTTP_PROXY'] = 'http://gateway.seb.zscaler.net:9480'

**Comment by blender** [comment] 2018-08-17 08:29
If it doesn't work in your enterprise network you have to work with your network admins.

As far as I can tell the proxy settings are picked up correctly.

**Comment by TeddyMalfroy** [comment] 2018-08-17 08:29
I also writes  : ENV['HTTPS_PROXY'] = 'http://gateway.seb.zscaler.net:9480' and it does not work.. The same if I launch in terminal directly : rome upload or rome download

**Comment by TeddyMalfroy** [comment] 2018-08-17 08:36
Error :  
(InternalException (HostCannotConnect "s3-eu-west-1.amazonaws.com" [Network.Socket.connect: <socket: 30>: does not exist (Connection refused)])))
10:35:05 2018-08-17 - Started downloading GSMODCache.369D9BB3-9F3C-345B-A512-38EB385CE387.bcsymbolmap from: GSMOD-iOS-Cache/iOS/369D9BB3-9F3C-345B-A512-38EB385CE387.bcsymbolmap-4.0.0.zip
10:35:05 2018-08-17 - Error: could not download GSMODCache.369D9BB3-9F3C-345B-A512-38EB385CE387.bcsymbolmap : TransportError (HttpExceptionRequest Request {
  host                 = "s3-eu-west-1.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Host","s3-eu-west-1.amazonaws.com"),("X-Amz-Date","20180817T083505Z"),("X-Amz-Content-SHA256","e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),("Authorization","<REDACTED>")]
  path                 = "/ios-prebuild-artifacts/GSMOD-iOS-Cache/iOS/369D9BB3-9F3C-345B-A512-38EB385CE387.bcsymbolmap-4.0.0.zip"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 0
  responseTimeout      = ResponseTimeoutMicro 70000000
  requestVersion       = HTTP/1.1
}

**Comment by blender** [comment] 2018-08-17 09:14
If it works __with a proxy in your home network__ and not in the enterprise network, then it's clearly a problem with your enterprise network

**Comment by TeddyMalfroy** [comment] 2018-08-17 11:51
Yes I'm sure! 
I have an another message in my terminal : 
Found GSMODDataTracking in local cache at: /Users/genesis/.ios_toolbox/GSMOD-iOS-SebAnalytics/iOS/GSMODDataTracking.framework-10.0.0.zip
rome: Carthage/Build/iOS/GSMODDataTracking.framework/SADebug.storyboardc/debug.nib: removeFile: permission denied (Permission denied).
It tells you something?

**Comment by blender** [comment] 2018-08-17 11:53
>Yes I'm sure!
Sorry, I didn't understand. You're sure about what?

> removeFile: permission denied (Permission denied).

Seems like the directory does not belong to the user running rome or you don't have enough permissions

**Comment by TeddyMalfroy** [comment] 2018-08-17 12:13
Yes I'm sure about the proxy, the mistake came from our company! 
Thanks for your help

**Comment by blender** [comment] 2018-08-17 12:16
@TeddyMalfroy Ok, so problems solved? I'm glad. :D

What company is this? 

Please close the issue if the problem is resolved.

**Closed** 2018-08-17 12:18 UTC
Labels: question
